<?php

namespace Database\Seeders; 

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Book;

class BooksTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('books')->insert([
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'publisher' => 'Secker & Warburg',
                'firstPubDate' => '1949-06-08',
                'ifTranslator' => 'original',
                'description' => 'A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.',
                'isbn' => '9780451524935',
                'pages' => 328,
                'ifChapters' => '-',
                'cover' => 'covers/1984.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'publisher' => 'J.B. Lippincott & Co.',
                'firstPubDate' => '1960-07-11',
                'ifTranslator' => 'original',
                'description' => 'A novel about the serious issues of rape and racial inequality.',
                'isbn' => '9780061120084',
                'pages' => 281,
                'ifChapters' => '-',
                'cover' => 'covers/to_kill_a_mockingbird.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'publisher' => 'Charles Scribner\'s Sons',
                'firstPubDate' => '1925-04-10',
                'ifTranslator' => 'original',
                'description' => 'A novel set in the Jazz Age that tells the story of Jay Gatsby\'s unrequited love for Daisy Buchanan.',
                'isbn' => '9780743273565',
                'pages' => 180,
                'ifChapters' => '-',
                'cover' => 'covers/the_great_gatsby.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'publisher' => 'T. Egerton, Whitehall',
                'firstPubDate' => '1813-01-28',
                'ifTranslator' => 'original',
                'description' => 'A romantic novel that charts the emotional development of the protagonist Elizabeth Bennet.',
                'isbn' => '9781503290563',
                'pages' => 279,
                'ifChapters' => '-',
                'cover' => 'covers/pride_and_prejudice.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'publisher' => 'Little, Brown and Company',
                'firstPubDate' => '1951-07-16',
                'ifTranslator' => 'original',
                'description' => 'A novel about teenage rebellion and alienation.',
                'isbn' => '9780316769488',
                'pages' => 214,
                'ifChapters' => '-',
                'cover' => 'covers/the_catcher_in_the_rye.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'War and Peace',
                'author' => 'Leo Tolstoy',
                'publisher' => 'The Russian Messenger',
                'firstPubDate' => '1869-00-00',
                'ifTranslator' => 'original',
                'description' => 'A novel that chronicles the history of the French invasion of Russia.',
                'isbn' => '9781420959719',
                'pages' => 1225,
                'ifChapters' => '-',
                'cover' => 'covers/war_and_peace.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Odyssey',
                'author' => 'Homer',
                'publisher' => 'Ancient Greece',
                'firstPubDate' => '0000-00-00',
                'ifTranslator' => 'original',
                'description' => 'An epic poem about the journey of Odysseus.',
                'isbn' => '9780140268867',
                'pages' => 541,
                'ifChapters' => '-',
                'cover' => 'covers/the_odyssey.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Crime and Punishment',
                'author' => 'Fyodor Dostoevsky',
                'publisher' => 'The Russian Messenger',
                'firstPubDate' => '1866',
                'ifTranslator' => 'original',
                'description' => 'A novel about the mental anguish and moral dilemmas of an impoverished ex-student.',
                'isbn' => '9780486415871',
                'pages' => 430,
                'ifChapters' => '-',
                'cover' => 'covers/crime_and_punishment.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Brothers Karamazov',
                'author' => 'Fyodor Dostoevsky',
                'publisher' => 'The Russian Messenger',
                'firstPubDate' => '1880',
                'ifTranslator' => 'original',
                'description' => 'A philosophical novel that enters deeply into the ethical debates of God, free will, and morality.',
                'isbn' => '9780374528379',
                'pages' => 796,
                'ifChapters' => '-',
                'cover' => 'covers/the_brothers_karamazov.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Brave New World',
                'author' => 'Aldous Huxley',
                'publisher' => 'Chatto & Windus',
                'firstPubDate' => '1932',
                'ifTranslator' => 'original',
                'description' => 'A dystopian novel about a future World State.',
                'isbn' => '9780060850524',
                'pages' => 311,
                'ifChapters' => '-',
                'cover' => 'covers/brave_new_world.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Wuthering Heights',
                'author' => 'Emily Brontë',
                'publisher' => 'Thomas Cautley Newby',
                'firstPubDate' => '1847-12-01',
                'ifTranslator' => 'original',
                'description' => 'A novel that explores the turbulent relationships between the characters.',
                'isbn' => '9780141439556',
                'pages' => 416,
                'ifChapters' => '-',
                'cover' => 'covers/wuthering_heights.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'publisher' => 'George Allen & Unwin',
                'firstPubDate' => '1937-09-21',
                'ifTranslator' => 'original',
                'description' => 'A fantasy novel about the adventures of Bilbo Baggins.',
                'isbn' => '9780547928227',
                'pages' => 310,
                'ifChapters' => '-',
                'cover' => 'covers/the_hobbit.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fahrenheit 451',
                'author' => 'Ray Bradbury',
                'publisher' => 'Ballantine Books',
                'firstPubDate' => '1953-10-19',
                'ifTranslator' => 'original',
                'description' => 'A dystopian novel about a future society where books are banned and "firemen" burn any that are found.',
                'isbn' => '9781451673319',
                'pages' => 194,
                'ifChapters' => '-',
                'cover' => 'covers/fahrenheit_451.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Grapes of Wrath',
                'author' => 'John Steinbeck',
                'publisher' => 'The Viking Press-James Lloyd',
                'firstPubDate' => '1939-04-14',
                'ifTranslator' => 'original',
                'description' => 'A novel about the struggles of a family during the Great Depression.',
                'isbn' => '9780143039433',
                'pages' => 464,
                'ifChapters' => '-',
                'cover' => 'covers/the_grapes_of_wrath.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Divine Comedy',
                'author' => 'Dante Alighieri',
                'publisher' => 'John Ciardi (Translator)',
                'firstPubDate' => '1320',
                'ifTranslator' => 'original',
                'description' => 'An epic poem that describes Dante\'s journey through Hell, Purgatory, and Paradise.',
                'isbn' => '9780451208637',
                'pages' => 798,
                'ifChapters' => '-',
                'cover' => 'covers/the_divine_comedy.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
